[FEAT] CENABLER-5386 - Prevent data loss / fix guide text & hints
digital-enabler/cost-benefit-analyzer pull request #23
Opened 2024-12-06 09:24 UTC by Dnikodij

# Hints

<img width="1512" alt="image" src="https://github.com/user-attachments/assets/a6ed7f48-1a99-4bfa-b692-75bb7659dbc1">

<img width="1512" alt="image" src="https://github.com/user-attachments/assets/cde7547e-0d05-45b4-8a19-6a340b80dc6f">

<img width="1512" alt="image" src="https://github.com/user-attachments/assets/36463236-6c05-43ea-b98e-7ad5970b9f45">

<img width="1512" alt="image" src="https://github.com/user-attachments/assets/220f93e9-e2f0-4a60-8ae1-a29d53e9cc49">

# Guide

<img width="1512" alt="image" src="https://github.com/user-attachments/assets/0b5daf74-c9ce-423c-8948-7e5d572e124d">

<img width="1512" alt="image" src="https://github.com/user-attachments/assets/a13cd3fd-7cf4-4103-a97e-3b1ca04f942c">

<img width="1512" alt="image" src="https://github.com/user-attachments/assets/a961b08b-9f97-40d9-a9cd-d26e1db0d827">

2024-12-06 13:40 UTC, nicolaleo approved these changes

2024-12-06 14:31 UTC, robraccu requested changes
Please, you have to add a versioning on package.json

2024-12-06 14:31 UTC, robraccu commented on app/src/components/HomePage.vue
> +  background: url('@/assets/i4n-keyvisuals-2022.jpg') no-repeat center center fixed;
If it not works...you can try using the public folder:
![image](https://github.com/user-attachments/assets/cd73f58d-1496-4839-9eac-e47c4b3152e1)

2024-12-06 15:50 UTC, Dnikodij commented on app/src/components/HomePage.vue
> +  background: url('@/assets/i4n-keyvisuals-2022.jpg') no-repeat center center fixed;
> If it not works...you can try using the public folder: ![image](https://private-user-images.githubusercontent.com/5311201/393285880-cd73f58d-1496-4839-9eac-e47c4b3152e1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM1MDA1MDIsIm5iZiI6MTczMzUwMDIwMiwicGF0aCI6Ii81MzExMjAxLzM5MzI4NTg4MC1jZDczZjU4ZC0xNDk2LTQ4MzktOWVhYy1lNDdjNGIzMTUyZTEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMDZUMTU1MDAyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWVmMDkzNmRlNDQyYTU4YjQ5Nzg0N2JmNGZmNmM5MDg0YzI5ZDY3ZGI3M2FhMmQ1ZjEzZTUxODhkMGQxYzkwZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.W6p05yq6Clb1XbfUeokzfc_LVBcqn2K3SO2tWkIaIP4)

i did use the public folder before this, when the image was in public folder it didnt work, now i moved it from public to assets..

2024-12-09 15:08 UTC, robraccu approved these changes

2024-12-10 08:34 UTC, merged